language: go
go:
  - "1.13"

env:
  - GO111MODULE=on

install:
  - go mod download
  - sudo mkdir /etc/fofo
  - sudo cp config.toml /etc/fofo/
  - go build -o fofo -i .

services:
  - redis-server
  - mongodb

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)