language: go
go:
  - "1.13"

env:
  - GO111MODULE=on

install:
  - go mod download
  - mkdir /etc/fofo
  - cp config.toml /etc/fofo/
  - go build -o fofo -i .

services:
  - redis-server
  - mongodb

script:
  - go test

after_success:
  - codecov